name: JoshRealmsMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 4.3
description: Plugin for the JoshRealms server.
softdepend: [BukkitTelnet, DisguiseCraft, WorldEdit, Essentials]
authors: [Madgeek1450, DarthSalamon]

# plugin.yml is no longer used to define commands.
